version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root@21!"
      MYSQL_DATABASE: "prova"
    ports:
      - "3306:3306"
    volumes:
      - /home/adriano/Documentos/images/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
      
networks: 
  mysql-compose-network:
    driver: bridge 
